### ISSUE TITLE
TODOs sould be fatal if they are silent failures

### ISSUE THREAD

**Issue by aleksanw** [stian-svedenborg/xyuv#9]
Noticed this silent failure here: [pixel_format_parser.cpp#L175](https://github.com/stian-svedenborg/xyuv/blob/891884b3cd3574ce7c488b504bcae76a3eac2d0a/xyuv/src/config-parser/pixel_format_parser.cpp#L175)

The program should terminate with an appropriate message.

**Comment by stian-svedenborg** [comment]
The backend support for that is actually already implemented, so it should be a quick fix.
